shell:
  program: /opt/homebrew/bin/fish
  args:
    - -l
    - -c
    - "/opt/homebrew/bin/tmux new -A -s dev"

window:
  dimensions:
    columns: 180
    lines: 60
  padding:
    x: 10
    y: 10
  dynamic_padding: true
  position:
    x: 0
    y: 0

font:
  size: 14
  normal:
    family: "JetBrains Mono"
    style: "Regular"
