# Gruvbox-inspired prompt
palette = "gruvbox_dark"

format = """
$directory\
$git_branch\
$git_status\
$python\
$golang\
$rust\
$nodejs\
$ruby\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold fg:bright-blue"
truncation_length = 3

[git_branch]
format = "[$symbol$branch]($style) "
style = "fg:bright-purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "fg:bright-yellow"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "
style = "fg:bright-yellow"

[python]
format = '[${symbol}${pyenv_prefix}(${version})]($style) '
symbol = " "
style = "fg:bright-yellow"

[golang]
format = '[$symbol($version)]($style) '
symbol = " "
style = "fg:bright-cyan"

[rust]
format = '[$symbol($version)]($style) '
symbol = " "
style = "fg:bright-red"

[nodejs]
format = '[$symbol($version)]($style) '
symbol = " "
style = "fg:bright-green"

[ruby]
format = '[$symbol($version)]($style) '
symbol = " "
style = "fg:red"

[palettes.gruvbox_dark]
bright-blue = "#83a598"
bright-cyan = "#8ec07c"
bright-green = "#b8bb26"
bright-purple = "#d3869b"
bright-red = "#fb4934"
bright-yellow = "#fabd2f"
