# ~/.tmuxinator/dev.yml
# you can make as many tabs as you wish...

project_name: dev
project_root: ~/Dropbox/code
windows:
  - editor: vim
  - shell: 
  - console: 
  - server: 
  - todo: vim todos.markdown
